ipv6: false
allow-lan: true
tcp-concurrent: true
external-controller: :9090
external-ui: ui
external-ui-url: https://zws.im/󠁨󠁵󠁮󠁺󠁣󠁱󠁢

find-process-mode: strict
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true

tun:
  enable: true
  stack: system
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-detect-interface: true

dns:
  enable: true
  ipv6: false
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
  nameserver:
    - https://8.8.8.8/dns-query
    - https://1.1.1.1/dns-query
  proxy-server-nameserver:
    - https://120.53.53.53/dns-query
    - https://223.5.5.5/dns-query
  nameserver-policy:
    "rule-set:cn_domain,private_domain":
      - https://120.53.53.53/dns-query
      - https://223.5.5.5/dns-query

http: &http {type: http, interval: 3600, health-check: {enable: true, url: https://cp.cloudflare.com, interval: 300}}
proxy-providers:
  SKYVPN:
    <<: *http
    url: https://zws.im/󠁫󠁥󠁲󠁢󠁷󠁹󠁸

  一元机场:
    <<: *http
    url: https://zws.im/󠁴󠁢󠁨󠁡󠁮󠁡󠁶

  百度直连:
    <<: *http
    url: https://zws.im/󠁳󠁺󠁡󠁫󠁶󠁵󠁸

proxy-groups:
  - name: 国内
    type: select
    proxies: 
      - PASS
      - DIRECT

  - name: 国外
    type: select
    use: 
      - SKYVPN
      - 一元机场

  - name: 百度
    type: select
    use: 
      - 百度直连

rules:
  - RULE-SET,private_ip,DIRECT,no-resolve
  - RULE-SET,秋风广告规则,REJECT

  - AND,((RULE-SET,cn_domain),(NETWORK,TCP),(DST-PORT,80/443/1024-65535)),百度
  - AND,((RULE-SET,cn_ip),(NETWORK,TCP),(DST-PORT,80/443/1024-65535)),百度

  - RULE-SET,cn_domain,国内
  - RULE-SET,cn_ip,国内

  - RULE-SET,geolocation-!cn,国外
  - MATCH,国外

rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  yaml: &yaml {type: http, interval: 86400, behavior: domain, format: yaml}
rule-providers:
  private_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"
  cn_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"
  geolocation-!cn:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"

  private_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs"
  cn_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"

  秋风广告规则:
    <<: *yaml
    url: "https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash.yaml"